CREATE DATABASE attendance_db;
USE attendance_db;

CREATE TABLE ADMIN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE EMP_INFO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL
);

CREATE TABLE EMP_POSITION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_ID INT,
    POSITION VARCHAR(50) NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO(ID)
);

CREATE TABLE PASS_KEY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_ID INT,
    FINGERPRINT VARCHAR(255),
    PIN_CODE VARCHAR(4) NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO(ID)
);

CREATE TABLE EMP_REC (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_ID INT,
    AM_IN TIME,
    AM_OUT TIME,
    PM_IN TIME,
    PM_OUT TIME,
    DATE DATE NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO(ID)
); 